#
# Jz47xx Platform Support
#
snd-soc-jz47xx-objs := jz47xx-pcm.o
snd-soc-jz47xx-i2s-objs := jz47xx-i2s.o

obj-$(CONFIG_SND_JZ47XX_SOC) += snd-soc-jz47xx.o
obj-$(CONFIG_SND_JZ47XX_SOC_I2S) += snd-soc-jz47xx-i2s.o

# Jz4760 Machine Support
snd-soc-lepus-icdc-objs := lepus_icdc.o

obj-$(CONFIG_SND_JZ4760_SOC_LEPUS_ICDC) += snd-soc-lepus-icdc.o

# Jz4770 Machine Support
snd-soc-pisces-icdc-objs := pisces_icdc.o

obj-$(CONFIG_SND_JZ4770_SOC_PISCES_ICDC) += snd-soc-pisces-icdc.o

# HIFI Machine Support
snd-soc-hifi-ecdc-objs := hifi_ecdc.o
obj-$(CONFIG_SND_SOC_HIFI_ECDC) += snd-soc-hifi-ecdc.o