
obj-y += core.o

obj-$(CONFIG_BATTERY_JZ47XX_ACT8600)	+= act8600_interface.o
obj-$(CONFIG_BATTERY_JZ47XX_ACT8600V2)	+= act8600_interfacev2.o
obj-$(CONFIG_BATTERY_JZ47XX_GPIO)	+= gpio_interface.o
obj-$(CONFIG_BATTERY_JZ47XX_FAKE)	+= fake_interface.o

