# Makefile for the jz4760 sound card driver
#
# 10 DEC 2010, <jbbi: jbbi@ingernic.cn>
#

obj-$(CONFIG_I2S_DLV_4760)	+= xb4760/
obj-$(CONFIG_I2S_DLV_4770)	+= xb4770/
obj-$(CONFIG_I2S_DLV_NPCA110P)	+= npca110p/
obj-$(CONFIG_I2S_DLV_TAS5713)	+= tas5713/
obj-$(CONFIG_I2S_DLV_ES9023)	+= es9023/
obj-$(CONFIG_I2S_DLV_WM8805_8740)	+= wm8805_8740/
obj-$(CONFIG_AK5358)		+= ak5358/

obj-y				+= jz47XX_i2s.o
#obj-y				+= jz47XX_bt_call.o
