
obj-$(CONFIG_VIDEO_ISP)		+= camera_source/isp/

#obj-$(CONFIG_VIDEO_JZ_CIM)		+= jz_cim_core.o jz_sensor.o 
obj-$(CONFIG_VIDEO_JZ_CIM)		+= jz_cim_core_v4l2.o jz_sensor.o 

obj-$(CONFIG_JZ4750_APUS)	+= jz_cim_board_apus.o
obj-$(CONFIG_JZ4750_AQUILA)	+= jz_cim_board_aquila.o
obj-$(CONFIG_JZ4760_ALTAIR)	+= jz_cim_board_altair.o
obj-$(CONFIG_JZ4760_PT701)	+= jz_cim_board_pt701.o
obj-$(CONFIG_JZ4760_LEPUS)	+= jz_cim_board_lepus.o
obj-$(CONFIG_JZ4760B_LEPUS)	+= jz_cim_board_lepus.o
obj-$(CONFIG_JZ4760B_LYNX)	+= jz_cim_board_lynx.o
obj-$(CONFIG_JZ4760_F4760)	+= jz_cim_board_f4760.o
obj-$(CONFIG_JZ4770_F4770)	+= jz_cim_board_f4770.o
obj-$(CONFIG_JZ4770_PISCES)	+= jz_cim_board_pisces.o
obj-$(CONFIG_JZ4810_F4810)	+= jz_cim_board_f4810.o

obj-$(CONFIG_VIDEO_BF3703)		+= camera_source/bf3703/
obj-$(CONFIG_VIDEO_OV2640)		+= camera_source/ov2640/
obj-$(CONFIG_VIDEO_OV9650)		+= camera_source/ov9650/
obj-$(CONFIG_VIDEO_OV7690)		+= camera_source/ov7690/
obj-$(CONFIG_VIDEO_OV3640)		+= camera_source/ov3640/
obj-$(CONFIG_VIDEO_OV2655)		+= camera_source/ov2655/
obj-$(CONFIG_VIDEO_CM3511)		+= camera_source/cm3511/
obj-$(CONFIG_VIDEO_JZ_FAKE_SENSOR)	+= camera_source/fake/
obj-$(CONFIG_VIDEO_JZ_TVP5150)		+= camera_source/tvp5150/
obj-$(CONFIG_VIDEO_GC0308)		+= camera_source/gc0308/
obj-$(CONFIG_VIDEO_GC0307)		+= camera_source/gc0307/
obj-$(CONFIG_VIDEO_GC0303)		+= camera_source/gc0303/
